/**
 * Sort direction understood by the provider-neutral DataGrid contract.
 */
export type GridSortDirection = 'asc' | 'desc';

/**
 * Backend-neutral operators used by global search and explicit column filters.
 *
 * Concrete providers translate these semantic operators into their own query
 * language; the DataGrid core must not introduce transport-specific syntax.
 */
export type GridFilterOperator =
  | 'eq'
  | 'ne'
  | 'contains'
  | 'startsWith'
  | 'endsWith'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'in'
  | 'sameDay';

/**
 * One typed provider-neutral filter condition.
 */
export interface GridFilter {
  field: string;
  operator: GridFilterOperator;
  value: unknown;
}

/**
 * Global-search request produced by the DataGrid.
 *
 * `conditions` are OR-ed together. This preserves the historic DataGrid
 * behavior where the same search text was translated per searchable column
 * (for example: string contains OR numeric equality).
 *
 * Column filters remain separate in `GridLoadRequest.filters` and are AND-ed.
 */
export interface GridSearch {
  value: string;
  conditions: GridFilter[];
}

/**
 * One normalized provider sort instruction.
 */
export interface GridSort {
  field: string;
  direction: GridSortDirection;
}

/**
 * Provider-neutral request generated by the DataGrid.
 *
 * `continuation` is intentionally opaque: a provider may use an offset,
 * cursor, page token or any other backend-specific continuation state.
 *
 * `search.conditions` represent one global OR group.
 * `filters` represent explicit column/base filters combined with AND semantics.
 */
export interface GridLoadRequest {
  pageSize: number;
  continuation?: unknown;
  search?: GridSearch;
  filters?: GridFilter[];
  sort?: GridSort[];
}

/**
 * Provider-neutral page returned to the DataGrid.
 *
 * `totalCount` is optional. When omitted, the grid derives the visual total
 * from the rows loaded so far and `hasMore`.
 */
export interface GridPage<T> {
  items: T[];
  hasMore: boolean;
  continuation?: unknown;
  totalCount?: number;
}

/**
 * Backend-neutral data source consumed by `DataGridComponent`.
 *
 * Implementations own transport details, authentication, endpoint selection,
 * row identity and backend-specific query translation. The grid passes complete
 * rows to mutations and must not assume an `id`, URL or database technology.
 */
export interface GridDataProvider<T> {
  /**
   * Loads one page using the normalized request produced by the grid engine.
   *
   * @param request Page size, opaque continuation and active query state.
   * @returns The rows plus provider-owned continuation metadata.
   */
  load(request: GridLoadRequest): Promise<GridPage<T>>;

  /**
   * Creates one row when the provider supports mutations.
   *
   * @param data Partial row supplied by the grid consumer.
   * @returns The authoritative row returned by the provider.
   */
  create?(data: Partial<T>): Promise<T>;

  /**
   * Updates one row without imposing any identity convention on `T`.
   *
   * @param data Complete row whose identity is interpreted by the provider.
   * @returns The authoritative updated row returned by the provider.
   */
  update?(data: T): Promise<T>;

  /**
   * Deletes one row without assuming a specific key field.
   *
   * @param data Complete row whose identity is interpreted by the provider.
   */
  delete?(data: T): Promise<void>;

  /** Deletes multiple complete rows in one provider-owned mutation. */
  deleteMany?(data: T[]): Promise<void>;
}
